### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by RepubblicaTech** [crcollins/pyOS#3]
Traceback (most recent call last):
  File "C:\Users\CraftMapping\Downloads\pyOS-master\pyOS.py", line 1, in <module>
    from kernel.system import System
  File "C:\Users\CraftMapping\Downloads\pyOS-master\kernel\system.py", line 135
    print "root %s has permisison for %s" % (laccess, path)

**Comment by crcollins** [comment]
Is there any more information? I thought this particular message was just a debug message I left in.

If you are using Python 3, this line will error due to print being changed from a statement to a function.

**Comment by RepubblicaTech** [comment]
Oh so i need python 2.7??

**Comment by crcollins** [comment]
Yeah, though, I do think an automated python 2to3 converter would probably work for this repo. I haven’t tested it though.
